version: '3.0'
services:

  mongo_db:
#    build: ./mongo
    hostname: mongo_db

    image: mongo:3.4.3
    restart: always
    ports:
      - "27017:27017"
    deploy:
      mode: global
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "root"

#  es-master:
#    image: elasticsearch:5.6.4
#    container_name: es-master
#    volumes:
##      - ./elasticsearch/node/es1/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/node/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ES_CLUSTERNAME=es-cluster
#    command: elasticsearch
#    ports:
#      - "9200:9200"
#      - "9300:9300"

#  es-node-01:
#    image: elasticsearch:5.6.4
#    container_name: es-node-01
#    volumes:
##      - ./node/es2/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/node/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ES_CLUSTERNAME=es-cluster
#    command: elasticsearch
#    ports:
#      - "9201:9200"
#      - "9301:9300"
#    links:
#      - es-master:elasticsearch

#  elasticsearch-head:
#    image: mobz/elasticsearch-head:5
#    container_name: head
#    volumes:
#      - ./elasticsearch/head/Gruntfile.js:/usr/src/app/Gruntfile.js
#      - ./elasticsearch/head/app.js:/usr/src/app/_site/app.js
#    ports:
#      - "9100:9100"
#    links:
#      - es-master:elasticsearch

  spark-master:
    hostname: spark-master
    image: singularities/spark
    command: start-spark master
    volumes:
      - ~/data/movies.csv:~/data/movies.csv
      - ~/data/ratings.csv:~/data/ratings.csv
      - ~/data/tags.csv:~/data/tags.csv
      - ./jars/dataloader-1.0-SNAPSHOT.jar:~/jars/dataloader-1.0-SNAPSHOT.jar
    ports:
      - "8020:8020"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
      - "8081:8081"
      - "9000:9000"
      - "10020:10020"
      - "13562:13562"
      - "14000:14000"
      - "19888:19888"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "50470:50470"
      - "50475:50475"
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == c1x132
#      mode: global

#  spark-worker-00:
#    image: singularities/spark
#    command: start-spark worker spark-master
#    environment:
#      SPARK_WORKER_CORES: 2
#      SPARK_WORKER_MEMORY: 2g
#    links:
#      - spark-master
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == c1x132

  spark-worker-01:
    hostname: spark-worker-01
    image: singularities/spark
    command: start-spark worker spark-master
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    restart: always
    links:
      - spark-master
    depends_on:
      - spark-master
    deploy:
      placement:
        constraints:
          - node.hostname == c2x133
#      resources:
#        limits:
#          cpus: '1'
#          memory: 4096M
#        reservations:
#          cpus: '0.5'
#          memory: 2048M
#      mode: global


  spark-worker-02:
    hostname: spark-worker-02
    image: singularities/spark
    command: start-spark worker spark-master
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    restart: always
    links:
      - spark-master
    depends_on:
      - spark-master
    deploy:
      placement:
        constraints:
          - node.hostname == c3x134
#      resources:
#        limits:
#          cpus: '1'
#          memory: 4096M
#        reservations:
#          cpus: '0.5'
#          memory: 2048M
#      mode: global



