version: '3.0'
services:

  mongo_db:
#    build: ./mongo
    image: mongo:3.4.3
    restart: always
    ports:
      - "27017:27017"
    deploy:
      mode: global
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "root"

#  es-master:
#    image: elasticsearch:5.6.4
#    container_name: es-master
#    volumes:
##      - ./elasticsearch/node/es1/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/node/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ES_CLUSTERNAME=es-cluster
#    command: elasticsearch
#    ports:
#      - "9200:9200"
#      - "9300:9300"

#  es-node-01:
#    image: elasticsearch:5.6.4
#    container_name: es-node-01
#    volumes:
##      - ./node/es2/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/node/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ES_CLUSTERNAME=es-cluster
#    command: elasticsearch
#    ports:
#      - "9201:9200"
#      - "9301:9300"
#    links:
#      - es-master:elasticsearch

#  elasticsearch-head:
#    image: mobz/elasticsearch-head:5
#    container_name: head
#    volumes:
#      - ./elasticsearch/head/Gruntfile.js:/usr/src/app/Gruntfile.js
#      - ./elasticsearch/head/app.js:/usr/src/app/_site/app.js
#    ports:
#      - "9100:9100"
#    links:
#      - es-master:elasticsearch

  spark-master:
    image: singularities/spark
    command: start-spark master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"
    deploy:
      placement:
        constraints:
          ## 常用方式指定 manager或者work节点placement:
          - node.hostname == c1x132

  spark-worker-01:
    image: singularities/spark
    command: start-spark worker spark-master
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
    links:
      - spark-master
    deploy:
      placement:
        constraints:
          ## 常用方式指定 manager或者work节点placement:
          - node.hostname == c1x132

  spark-worker-02:
    image: singularities/spark
    command: start-spark worker spark-master
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    links:
      - spark-master
    deploy:
      placement:
        constraints:
          ## 常用方式指定 manager或者work节点placement:
          - node.hostname == c2x133
          # - node.role == worker


  spark-worker-03:
    image: singularities/spark
    command: start-spark worker spark-master
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    links:
      - spark-master
    deploy:
      placement:
        constraints:
          ## 常用方式指定 manager或者work节点
          - node.hostname == c3x134
          # - node.role == worker



