version: '3.0'
services:
  spark-worker:
    image: singularities/spark
    container_name: spark-worker
    command: start-spark worker spark-master
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    links:
      - spark-master

networks:
  cluster:
    external: true